language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
env:
  global:
    secure: MnEEAbY8kLjowi0MXTI9Ugt8uZK23ufKv/Z4XVxjBxus9elOPM7WSUx9XoYnA/me+xLQvrPi9loLCRiK7KKhButLKsmA8hokezTN/EWpkKnP3I1BUeel6BJmSsL1mnSIx+ldLzaBByPvHIjGTjt2dzSOWVDPPAwFlLXE3laN2Yt0HnEGX2mPJ/Gv3uy7oW4bwRNGqnVbpoVMIN64EVMBmxafCl9VHRGBUtmSYgFCzzEF8EUpZ2R115rXo8XQqr7bconX2BwDxRTxwr79UfwQPvl4p8agXNi1d+27cMHf0DBFKEM/PrlOmt1XueVUh5hQxgUdrE0Nkb+t6W7TL0Po6VLTKcFy3kT/nS6DuAn9q8+KX+r4BJgjb/UZx6+C+r6ppjlMrdv1/6DmwiIE0QYju5uc7aVlWCcOxhb6XWxpqWmfj15DJGAxO9Pj+2kULTKa1CJvALBPN7sW2B+5H1+/Zt5D6dcHdiErekFzXM3zA/SQZZ7ie3A3Ffe4DLO2oDhrb1A5+xDxqBru28/2mz3kZa9xt91fNTQGo/2+2a6mr/rngoD6FjBhopRiYOkq+cCm87yC5Lc6M1jojohFrhPASUoh5JbngBDmBr+kgExrrDvUIiThtKnFgtlSVu+1ohi5sODt7hJJY7Ac9vusHHwxXxP6jdLH/4N5cQE+YDzL5HQ=
