language: node_js
node_js:
    - 10.8.0
cache:
    directories:
        - node_modules
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $REACT_APP_GITHUB_API_TOKEN
    keep-history: true
    target-branch: master
    on:
        branch: development
