language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
env:
  global:
    secure: 1knXvylY+JoUumer+alnLXNgFyqmr/uqu4ryRNo9kYxRg4mnQXva4eTdZ9dHfA5AZ+r3CB87OuasAz6WNHs6MN7K5r6NtENDK1lfy/4nXhCtIMXvc9lYgqe1ghSmnTxhL8OW0IbtoukMlrxZpg71h5LszbXT2YB1ZARkdkKrsAkbRawfj1+r00w51KW/08KMe7CDkvO+ShzWdntxjtfulAq/LUAeAtyxhBVPSOYmte7kpgFmyskox3oK8UObwWV5F0ueMOUssSeEJVtmm781TJOLCq2csU6ARZPtjh18qecrigs0zQU5D8ArQtiOegLgF1v8nptv5odbd8pM1lK6CIbQIwJyctaJTgQqtnVfNqpG/m+2VGkQ2jKlP420DgR4aukywaos7j9BlBaySrcAYRFcsqKrSG/9WbuUuhdHYg/vgYEsl5Oq96eys/KTotZ+zSgUpBicmzIin33QXz4TPoCyPMBJpdKhnGc6RbWq0sYnNSYb2GYATzhJFd8LgsCt6Sr2+y843beXuAxoRR0hXmnf0F7roHdfBs1InHxkRmND6a/NhVlQ0m2bMdcBIZ24eDQJA23KX0+6+DqpVARQaWX4qayLHX+XXZwgD7rKdfdNIkB8rmb9MyvQlYB9hJLOR3XHEn8LEZjmAXDaX/os1YiIdJKrDOkSznJIQ8/AXBM=
