language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
env:
  global:
    secure: V0zEh7qJF3xrLgPjZIRgU7DqJB+dNFVd7GFgBPPCrYpLT7CF+Ci2MIi3l8srXU0vDcFR2eWTry3/odoDuXeskspBuIFuuA59ehTwLY5hi10PtqEC/OqBP2KYroGrB/0Umjt1TvQbwvR6368FkcV4XZjIoJujcpqoPwFQK2ZdRqlvhelCeL9206zIfPGU0/Qd7eVvIi1sdJGzsIEvrwEsq1tLUyCeFCcKxFVfGpd8HZEyAxhxr90Tg0NLgMAIjXHAwaC51oyIAeBmLvyOSx88+8RvXub4mMnQaU43FPC7Ulun9K4+P5vnSQYeWkg4Vrd/vR4MumaOugywxYHud5Ffw1PcJ9A/1z04tn+pGtAJwD3gi94H+a4IXfbjQvL1n3Ej7dNhCnmhtIYcWKzKXtbfmQFv0SmEKuKNlvw7uejk5m6yaI4r9iBeEGNq1f+1s51mw28EjMtJrfC40onf61lIEqZm2FlpgS9S8CepwuMge+N31CHQdloFsPOZMWAPGJuUf2UzYfodKH2OwXS0f+P/cX3rFH7fRgicRVPmpb5EYcvDkWNdJ46oqoZhRJdPlO5Cjo2/NG6P/DjQQsA86gQQxD/7XjIYnKXrtZ51qPeco0INvwERU2mRSg3Sg6GoNd/MK8po+YMf6Ha0oRNfk+Yr/MYET5mLm4He1Ur6FY6SgyA=
