language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
env:
    global:
        secure: C3OmOsieMNfCyAov96cUXxDZPBAck9QKUirViUj2qxQje0e9WUdGM4Eg4b37ayJZiJo99DAiskplIrc5+PGo7zAD6xVGEYOSRGdpmRoqHDGEDRhc8XMCmQc1wuhFthkSrbDGV/ZrByg4C+e28fdIWKzL/8j9V8Q7FSvlsD4NUa+Rf5ACQEWCMo7SIgRj/Hp7JNSjeS1abwnBBDQAdwopvMx08RPlyrDxYnhjOWKAkr7TH/9Y0dhjeu96fcJuFjJzs/2FwHcPVq4ZpacmlQlH6/80hjJ7tLmdDlGvuflJAOmvPFaswI5SmDQKGsiV4yZDZeXDnjlnFcBsV2zHHa6ILISLx/5GaaJIItVabWBT+is2tnJp7YdwpbUK+eOb8OXB2z2gMtRkbk/MzNm6GPG719wFu+ueUaYwpQBeI7G5WqRdDBIh4nAJuIVASllc1bVEnvjG7nv6AVn+BcAiUEFCx4OwA0d6aCYxmfSSRtZVhlAw5AMrWSlydTbwnW8Dg/VbtZ3MjMy1lcr/TtGuSOkp4e9pwpL8OoiZMM0zUK950CBW64nhkEfQIlMBVwJIfUNo6P65fDsgIeRgAyO9p9KpCZU2eofFAAYE/C0sAKrBtEpg3l9QLcxY9f/Gt+WRzXp0qsXOLU0/EtR5zkdskNR8fLsBWejFv/EFMgUxhbxc8K0=
