language: node_js
node_js:
    - 'node'
cache:
    directories:
        - 'node_modules'
secure: 'HPT4Dos9GTXxpjYOP9qkaGN1Zmr1BJfJgg283N4eHVSl8+o5VsJR5JAkAh54Sb5PNcE35+tDkB4XwzIHywJkJWZ2FeJvphtn56FUJUdTx21aPz/uKnu/ZS67ZjuuW4hU/yiiWnFnCapNRm/oYd6nZjzOn2iqYxoG6ba1ZVc682MpU+RWoP2dXlsmmfC9uf2jcVUakVUuyqz8auaWwUNWq3an58mHnguwWaGMhHMBwnxE80PAOBivbnmpZW93KQbGZlwOK1pr9/KX1FrEvw6nMMBmHDgAaAL6hgf31DZetIv0+0FzNS2+xzA8ow7VnKCPwVw4Duc0yPgo5QlirkltYVXmFtI2dGGWzn7EAbEA+Lz53e7zTUQJ15MpHEXtdqic/TJVmT/ZiY17jKcvJaf9rknvpVYxBl8kEe/l2baiFvocLuaTWGUSHBaqKRDMnn0J8n6j3RDQgA/Pj3LHteRtyl7lv8bOuNQmHmFTgreZaUurm5Ot0NP5kKH60FGXtaYDd7fGaKHFgCZy22P+8oKbQ8tLJ7hVT4/f0TquypGhUgP1Ea9OexUscSSY2M6wJti0gBsQ0IPat4IU2L/OE4vLpgtuxRBehpq83GVL/sdu9so3fBYm+5U9LPNdmTpymuN2WkPSvUTB2rkqBbXakQAcJUQ92gbqk5aL+xeqVbMims8='
