warnings_are_errors: false
language: node_js
node_js:
    - 10.8.0
cache:
    directories:
        - node_modules
script:
    - yarn test
    - yarn build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: '$REACT_APP_GITHUB_API_TOKEN'
    keep-history: true
    target-branch: master
    verbose: true
    local_dir: build
    on:
        branch: development
env:
    secure: Azim+Cjs17mpLCYR4rXwcZMZReM69EgiJSHF/fidEArih3/UzNETMEsugW5Dgcem3xOIi+3qw5cU61cqhmd19/B/zoJSLnBV534fFXCWh6wpbByXWP29Ri+FUDqrD7Px3AvWbTDVew6A61ue/JJoWLY1+AJ10J+ZHvA5ChSbhxf5qpeT4r8WLt21NWV7AKo/umKXZ4jvuf/oMXVXSYcHoS69CYytl5wjJrI5vzu+/wF8xdFkjiuWinufxgkFgoH8uUTeoO+u5AsyzQctEpWxzEvlhCa+er9ceXj/xcBU0z4PWQdBOzo5jk8dchyTN7vHFZXdJYqP3kHahIz61p+kA6mgRh3N8hHN7b9MXlxuVnQ7CXDl407bq1XjuwDWl3HiCuzMsLW7Q3dFduZ/m9CUGwQVkSJ5M0LF8ZcslxVxpBbkGVO6mQ0dg1iygypYXnlLCbWZYsSgDC36HxytrGmLeJxkUUZukhSAvQJ/5O6IxDU4pgjavnwnHA5OZsBYJMTHc6Xp/kxyR3FkhOzdSmR1u42/h8N73wLkQDn0VWUvPMrVnLZrIu/XsWvYDS8xooWxnuVfW6t6KhHeWZH70TK/G1aurjO3qzHbWoA50oLKm2rVl2WIldQhAVQrF9rJ9P4ZKy6pEF7OJOy/A5J9szg6c4FCloGsGvT+2V9BgnYgcyc=
